### ISSUE TITLE
Add the release please configuration

### ISSUE THREAD

**Issue by kaariger** [elatovg/terraform-google-secretmanager#4]
Please add the release please configuration to help with releasing the module. Please see the example config [here](https://github.com/terraform-google-modules/terraform-google-module-template/blob/master/terraform-google-%7B%7Bcookiecutter.module_name%7D%7D/.github/release-please.yml) in the [template module](https://github.com/terraform-google-modules/terraform-google-module-template)

**Comment by elatovg** [comment]
fixed by #8
