### ISSUE TITLE
Modify module outputs

### ISSUE THREAD

**Issue by kaariger** [elatovg/terraform-google-secretmanager#6]
Please make the outputs from the module computed attributes only.

- [ ]  Only name should be output and not all the values. Please [see here](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/secret_manager_secret#attributes-reference) for a list of computed attributes.
- [ ] Module creates a secret version. So output the name of the secret version as well. Please [see here](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/secret_manager_secret_version#attributes-reference)

**Comment by elatovg** [comment]
As of right now the outputs looks like this:

```
Outputs:

secret_names = [
  "projects/PROJ_NUM/secrets/secret_1",
  "projects/PROJ_NUM/secrets/secret_2",
  "projects/PROJ_NUM/secrets/secret_3",
]
secret_versions = [
  "projects/PROJ_NUM/secrets/secret_1/versions/1",
  "projects/PROJ_NUM/secrets/secret_2/versions/1",
  "projects/PROJ_NUM/secrets/secret_3/versions/1",
]
```

What would you liked included?

**Comment by kaariger** [comment]
The output looks good. Thanks.
