### ISSUE TITLE
Change secrets from a list of objects to a list of maps of type string

### ISSUE THREAD

**Issue by kaariger** [elatovg/terraform-google-secretmanager#7]
- [ ] Secrets variable [list of objects](https://github.com/elatovg/terraform-google-secret-manager/blob/ecc2f07a54338c6e7e18268dcf7f104039615003/variables.tf#L22) is too complicated to use. Additionally, since some of these values are null, it would be better to switch this to a list of maps of type string. [See subnets](https://github.com/terraform-google-modules/terraform-google-network/blob/1eda9d9b5c2a2c910015e9fa605fe2142a2ef393/modules/subnets/variables.tf#L25) as an example of how to use the map of string type.
- [ ] [Nested objects](https://github.com/elatovg/terraform-google-secret-manager/blob/ecc2f07a54338c6e7e18268dcf7f104039615003/variables.tf#L26) should be elevated up to the map such that it doesn't have any nested objects. For example: user_managed_replication_location and user_managed_replication_kms_key_name should be used.

**Comment by elatovg** [comment]
Hey @kaariger thanks for reviewing this. One quick clarification on the second task. The main reason I kept the nested objects is in case the object has a new field added later on, then we can just keep using the object and not have to update our code to accommodate the new field. Is it typical to expand the nested objects for our modules, it seems like this will create more work for us down the line. Please let me know your thoughts.

**Comment by elatovg** [comment]
@kaariger, just to make sure I am going down the right path, we are going from:

```    
user_managed_replication = [
    {
      location     = "us-central1"
      kms_key_name = "projects/project-demo/locations/us-central1/keyRings/us-central1-keyring/cryptoKeys/cool"
    },
    {
      location     = "us-east1"
      kms_key_name = "projects/project-demo/locations/us-east1/keyRings/us-east1-keyring/cryptoKeys/cool"
    }
 ]
```

To this:

```
user_managed_replication_1_location = "us-central1"
user_managed_replication_1_kms_key_name = "projects/project-demo/locations/us-central1/keyRings/us-central1-keyring/cryptoKeys/cool"
user_managed_replication_2_location = "us-east1"
user_managed_replication_2_kms_key_name = "projects/project-demo/locations/us-east1/keyRings/us-east1-keyring/cryptoKeys/cool"
```

Is that right?

**Comment by kaariger** [comment]
> Hey @kaariger thanks for reviewing this. One quick clarification on the second task. The main reason I kept the nested objects is in case the object has a new field added later on, then we can just keep using the object and not have to update our code to accommodate the new field. Is it typical to expand the nested objects for our modules, it seems like this will create more work for us down the line. Please let me know your thoughts.

Hi @elatovg you can use the nested properties. Just convert them to a list of maps i.e. list(map(string))
